---

- name: Install curl gnupg2 ca-certificates lsb-release keyrinig Ubuntu
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install curl gnupg2 ca-certificates lsb-release keyrinig Debian
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - debian-archive-keyring
    state: present
  when: ansible_distribution == 'Debian'

- name: "add key gpg repo nginx"
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /usr/share/keyrings/nginx-archive-keyring.gpg
    mode: '0644'
    
- name: "add key repo nginx"
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: repo nginx 
  ansible.builtin.apt_repository:
    repo: deb http://nginx.org/packages/mainline/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx
    state: present

- name: "Update apt packages Install nginx"
  ansible.builtin.apt:
    name: "nginx={{ v_nginx }}"
    state: present
    update_cache: true
    
- template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ name_conf_nginx }}.conf
    owner: user
    group: user
    mode: '0644'
    backup: yes

- name: "Creates directory"
  ansible.builtin.file:
    path: /data/myweb/www
    state: directory
    owner: user
    group: user

- name: "Copy our html to /data/myweb/www file"
  ansible.builtin.copy:
    src: "index.html"
    dest: "/data/myweb/www"
    owner: user
    group: user
    mode: 0644